a200_0000:
  ekf_node:
    ros__parameters:
      odom_frame: 'odom'
      base_link_frame: 'base_link'
      world_frame: 'odom'
      publish_tf: True
      two_d_mode: False
      use_sim_time: True
      frequency: 50.0
      odom0: 'ground_truth/odom'
      # [x,    y,    z,    roll, pitch, yaw,  vx,   vy,   vz,   vroll, vpitch, vyaw, ax,    ay,    az   ]
      odom0_config: [True, True, True, True, True, True, True, True, True, False, False, True, False, False, False]
      odom0_differential: False
      odom0_queue_size: 10
